# Dockerfile
#
# Linux development environment
#
# Extend the miracl/alldev image defined in
# https://github.com/miracl/alldev
# ------------------------------------------------------------------------------

FROM miracl/alldev
MAINTAINER nicola.asuni@miracl.com
